---
extends: fbjs
env:
  node: true
rules:
  no-eval: warn
  no-undef: warn
  no-unreachable: warn
  max-len:
    - warn
    - ignoreComments: true
      ignorePattern: ^import\s.+\sfrom\s.+;$
      ignoreStrings: true
  radix:
    - warn
    - as-needed: true
